package com.ops.zen.jdbc;

/**
 * @Author xyn
 * @Date 2025/04/20 10:58
 * @Description
 */
public enum CastEnum {
    UNWRAP_INT, UNWRAP_BYTE, UNWRAP_LONG, UNWRAP_DOUBLE, UNWRAP_SHORT, UNWRAP_FLOAT,
    UNWRAP_BYTE_ARRAY,//BLOB
    WRAP_INT, WRAP_BYTE, WRAP_LONG, WRAP_DOUBLE, WRAP_SHORT, WRAP_FLOAT, WRAP_BYTE_ARRAY,
    BIGDECIMAL,
    BIGINTEGER,
    STRING,//普通String和CLOB
    STRINGBUILDER, STRINGBUFFER,
    DATE,
    LOCALDATETIME,
    WRAP_BOOLEAN,
    UNWRAP_BOOLEAN,
    WRAP_CHAR,
    UNWRAP_CHAR,
    INPUTSTREAM;
}
