#######默认配置,可以通过添加beetl.properties覆盖这些配置
#注释可以是/**/也可以是//，但是使用时必须放在定界符内，放在外面会作为文本输出
ENGINE=org.beetl.core.engine.FastRuntimeEngine
DELIMITER_PLACEHOLDER_START=${
DELIMITER_PLACEHOLDER_END=}
DELIMITER_STATEMENT_START=--
DELIMITER_STATEMENT_END=

DELIMITER_STATEMENT_START2=<%
DELIMITER_STATEMENT_END2=%>

#DELIMITER_PLACEHOLDER_START2=${
#DELIMITER_PLACEHOLDER_END2=}


ERROR_HANDLER = org.beetl.core.ReThrowConsoleErrorHandler
